import { Open_Sans } from "@next/font/google";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const openSans = Open_Sans({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <style jsx global>{`
        html {
          font-family: ${openSans.style.fontFamily};
        }
      `}</style>

      <Head>
        <title>Australian Tattoo Expo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${openSans.className}`}>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus ratione
          porro impedit obcaecati quo, non dolore accusamus, quisquam
          aspernatur, veritatis nulla culpa odit officia eos delectus neque
          architecto iure dolorum.
        </p>
      </main>
    </>
  );
}
