// Generated by https://quicktype.io

export interface GetArtistsByEvent {
  page: Page
  posts: Posts
  tattooTaxonomies: TattooTaxonomies
}

export interface Page {
  eventsContent: EventsContent
  __typename: string
}

export interface EventsContent {
  featured: Featured[]
  __typename: string
}

export interface Featured {
  slug: string
  title: string
  uri?: string
  acfFeaturedImage: AcfFeaturedImage
  artist: Artist
  __typename: FeaturedTypename
}

export enum FeaturedTypename {
  Artist = "Artist",
}

export interface AcfFeaturedImage {
  profileImage: ProfileImage
  __typename: AcfFeaturedImageTypename
}

export enum AcfFeaturedImageTypename {
  ArtistAcffeaturedimage = "Artist_Acffeaturedimage",
}

export interface ProfileImage {
  altText: AltText
  sourceUrl: string
  title: string
  __typename: ProfileImageTypename
}

export enum ProfileImageTypename {
  MediaItem = "MediaItem",
}

export enum AltText {
  Empty = "",
  Troyslackink = "troyslackink",
}

export interface Artist {
  studioName: string
  __typename: ArtistTypename
}

export enum ArtistTypename {
  ArtistArtist = "Artist_Artist",
}

export interface Posts {
  artists: Artists
  name: string
  slug: string
  __typename: string
}

export interface Artists {
  edges: Edge[]
  pageInfo: PageInfo
  __typename: string
}

export interface Edge {
  node: Featured
  __typename: string
}

export interface PageInfo {
  hasNextPage: boolean
  endCursor: string
  __typename: string
}

export interface TattooTaxonomies {
  nodes: Node[]
  __typename: string
}

export interface Node {
  name: string
  taxonomyName: string
  __typename: string
}
